### ISSUE TITLE
[Page] 페이지 전환 #11

### ISSUE THREAD

**Issue by KimPilGyeom** [DeveloperAcademy-POSTECH/2024-NC2-A43-CoreBluetooth#11]
## About
각 페이지 전환 잘 이뤄지게

## Branch Name
Page/#6-Pagechange

## Todo
- [ ] 페이지 전환 알고리즘 수정하기
- [ ] 전환 기준 수정하기
- [ ] 해제 후 시간 측정 및 표시 잘 표현하기
- [ ] 햅틱 연결하기
